apiVersion: v1
kind: Secret
metadata:
  name: app-database-secret
  namespace: lab5-app
  labels:
    app: advanced-app
    component: database
type: Opaque
data:
  # Base64 encoded values
  # echo -n "myuser" | base64 => bXl1c2Vy
  # echo -n "mypassword" | base64 => bXlwYXNzd29yZA==
  username: bXl1c2Vy
  password: bXlwYXNzd29yZA==
  host: bXlkYi1wb3N0Z3Jlc3Fs
  port: NTQzMg==
  database: YXBwZGI=
