replicaCount: 5

image:
  repository: nginx
  tag: "1.22"

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

app:
  environment: production
  logLevel: warning
