{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lab6-handons.fullname" . }}-frontend
  labels:
    {{- include "lab6-handons.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "lab6-handons.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "lab6-handons.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: BACKEND_API_URL
          value: "http://{{ include \"lab6-handons.fullname\" . }}-backend:{{ .Values.backend.service.port }}"
        - name: APP_NAME
          value: {{ .Values.app.name | quote }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
{{- end }}
