{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lab6-handons.fullname" . }}-db-secret
  labels:
    {{- include "lab6-handons.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.database.username .Values.database.password .Values.database.host .Values.database.port .Values.database.name | b64enc | quote }}
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
