{{- if .Values.result.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app.fullname" . }}-result
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: result
spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      {{- include "voting-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: result
  template:
    metadata:
      labels:
        {{- include "voting-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: result
    spec:
      containers:
      - name: result
        image: "{{ .Values.result.image.repository }}:{{ .Values.result.image.tag }}"
        imagePullPolicy: {{ .Values.result.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.result.service.targetPort }}
          protocol: TCP
        env:
        - name: POSTGRES_HOST
         value: "{{ .Release.Name }}-postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.auth.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.auth.database | quote }}
        resources:
          {{- toYaml .Values.result.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-result
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - port: {{ .Values.result.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: result
{{- end }}
