{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lab5-handons.fullname" . }}-db-secret
  labels:
    {{- include "lab5-handons.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
  host: {{ .Values.database.host | b64enc | quote }}
{{- end }}
